name: Deploy MERN Backend to EC2

on:
  push:
    branches:
      - main # deploy when code is pushed to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 4. Deploy to EC2 using SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Connected to EC2..."

            # Go to your project root
            cd /home/ubuntu/deskopsdemo

            # Pull latest code
            git pull origin main

            echo "Updating backend..."

            # Backend
            cd backend
            npm install

            # Restart backend using PM2 (use your real entry file name)
            pm2 restart server.js

            echo "Updating frontend..."

            # Frontend
            cd ../frontend
            npm install
            
            npm run build

            # Copy React build to Nginx folder
            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html/

            # Reload Nginx
            sudo systemctl reload nginx

            echo "Deployment completed successfully ðŸš€"



# name: deployment

# on:
#   push:
#     branches:
#       - main
# jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: ssh ec2
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
              echo "Connected to EC2..."

              # Go to your project root
              cd /home/ubuntu/deskopsdemo

              # Pull latest code
              git pull origin main

              echo "Updating backend..."

              # Backend
              cd backend
              npm install

              # Restart backend using PM2 (use your real entry file name)
              pm2 restart server.js

              echo "Updating frontend..."

              # Frontend
              cd ../frontend
              npm install
              
              npm run build

              # Copy React build to Nginx folder
              sudo rm -rf /var/www/html/*
              sudo cp -r dist/* /var/www/html/

              # Reload Nginx
              sudo systemctl reload nginx

              echo "Deployment completed successfully "